### PR TITLE
Downgrade phpunit

### PR DESCRIPTION
**Pull request by b1rdex**
I tried to rewrite the tests in #629 and found it very hard.
IMO we should better stay at PHPUnit 4.8 for now then have all the tests broken.

### CODE REVIEW

**Comment by AhmedRaafat14** [comment]
Hmm so this means we drop updating the tests and stick to PHPUnit 4?!
> what we discuessed [here](https://github.com/predishq/predis/issues/620#issuecomment-672960734)

**Comment by b1rdex** [comment]
I'd propose staying on the PHPUnit 4 for now. Just to have the tests passing.
Then we can upgrade it in a PR, rewriting/fixing all the tests.

**Comment by AhmedRaafat14** [comment]
> I'd propose staying on the PHPUnit 4 for now. Just to have the tests passing.
> Then we can upgrade it in a PR, rewriting/fixing all the tests.

I agree but that was the plan for v2.2, we kept it as it is for v1.1 now.

Maybe @tillkruss have a different opnion! lets see what he thinks.

**Comment by b1rdex** [comment]
I see no point in having the main branch tests broken.
I'm not against upgrading phpunit, I just want to have the tests working to check new code/fixes.

**Comment by AhmedRaafat14** [comment]
> I see no point in having the main branch tests broken.
> I'm not against upgrading phpunit, I just want to have the tests working to check new code/fixes.

yes I agree with you it should be working and someone else doing the tests update.

My point was to see if we really have to do the upgrade or not will keep it like this in v2, will see.

**Comment by nrk** [comment]
> I'd propose staying on the PHPUnit 4 for now. Just to have the tests passing.
> Then we can upgrade it in a PR, rewriting/fixing all the tests.

@b1rdex I agree. I mean I **do** think we should upgrade to a newer PHPUnit version for Predis v2.0 but I just don't see the point of doing it right now if PHPUnit 4 still works with PHP 7.4 / PHP 8.0 after patching. Investigating on what needs to be done for the upgrade is fine, obviously, but doing the actual work of rewriting tests should be done when the codebase on `main` will be stable enough in terms of changes in order to avoid wasting time.

On a kind of related note, I understand the excitement of reviving Predis and it's awesome but IMHO we are going a bit too fast and sometimes getting too trigger-happy with merges and commits, for no practical reasons. Clearly this doesn't mean we should stick with how I was getting things done back when I was actively working on this library alone, it wouldn't work now and I was probably doing the exact opposite to the extreme anyway (test stuff locally first on multiple runtimes, think about changes twice or thrice for a few days and then finally push stuff). Just my point of view, that goes without saying 😉

> My point was to see if we really have to do the upgrade or we will keep it like this in v2, will see.

@AhmedRaafat14 it really depends on the effort required for upgrading to a newer PHPUnit, but I think it will be worth doing so for v2.

**Comment by AhmedRaafat14** [comment]
@nrk I completely agree with you as we decided to get a little bit slow, I also would love to merge this PR at least to have a successful build on the main branch so people can feel trusty on their code changes exactly as @b1rdex suggested.

Also, I will take a lazy approach to upgrade PHPUnit and fix the tests step by step as we go & will always rebase to latest changes on the main so be inline with the code changes and not get many merge conflicts at the end 😅.

**Comment by tillkruss** [comment]
I agree with upgrading PHPUnit and fixing the tests slowly over the next weeks. No rush, but keeping PHPUnit v4 going seems like dragging on baggage.

**Comment by tillkruss** [comment]
Should we merge #629 in the meantime to fix up some of the tests?

**Comment by tillkruss** [comment]
@predishq/team If any of you want to jump in on fixing up the tests piece by piece, please go for it 🙌🏻

**Comment by AhmedRaafat14** [comment]
> @predishq/team If any of you want to jump in on fixing up the tests piece by piece, please go for it 🙌🏻

I was planning to do it :)

**Comment by emmanix2002** [comment]
@AhmedRaafat14 LOL! I started on that this morning. I can drop it if you want to though.

**Comment by AhmedRaafat14** [comment]
> @AhmedRaafat14 LOL! I started on that this morning. I can drop it if you want to though.

Hahah no problem move on :)

Ping me if you need my help :)

**Comment by emmanix2002** [comment]
@AhmedRaafat14 ok, I'll keep you in the loop.

**Comment by nrk** [comment]
I still don't understand why we didn't proceed with #630 (this PR) to revert to a working test suite first and then do the grunt work of converting the whole set of tests to the new framework on a separate PR to be merged at a later stage, but oh well if there's someone already working on it I guess it's fine 😃 I'm going back to recovering stuff from `master-stale` in the meanwhile 😉

**Comment by srmklive** [comment]
As defined in v2 Roadmap in #615. The base PHP version would be 7.2 for v2. My suggestion is that we keep PHPUnit version to 6 (PHP 7) minimum for v2.

**Comment by nrk** [comment]
> As defined in v2 Roadmap in #615. The base PHP version would be 7.2 for v2. My suggestion is that we keep PHPUnit version to 6 (PHP 7) minimum for v2.

@srmklive but [their matrix](https://phpunit.de/supported-versions.html) says that PHPUnit 8 supports PHP versions starting with 7.2 which will be our minimum target for v2 as dicussed. It's totally possible I'm missing something, but what would be the advantage of going with PHPUnit 6?

**Comment by srmklive** [comment]
@nrk my view is there might be a lot of application using Predis on 7.0 & 7.1 that are using v1.1. But once v2 is released, they may want to use v2 in their applications.

**Comment by tillkruss** [comment]
People running 7.0 and 7.1 are probably also fine with running Predis 1.x, no?

**Comment by b1rdex** [comment]
> @nrk my view is there might be a lot of application using Predis on 7.0 & 7.1 that are using v1.1. But once v2 is released, they may want to use v2 in their applications.

@srmklive phpunit is a dev dependency. It doesn't affect root composer package restrictions.

**Pull request closed without merging**
