### PR TITLE
Fix php version requirement

### PR DESCRIPTION
**Pull request by b1rdex**
I'm not sure how to specify it better: `>=7.2` or `^7.2 | ^8.0` or `>=7.2 <9`.
`>=7.2` looks OK for me now.

### CODE REVIEW

**Comment by b1rdex** [comment]
Without this composer fails to `install`: https://travis-ci.org/github/predishq/predis/jobs/717492543

**Comment by AhmedRaafat14** [comment]
But even you still have a build issue is it related to #630!

**Comment by b1rdex** [comment]
True. #630 is first to merge.

**Comment by b1rdex** [comment]
This change must be applied even if we stick with phpunit 8.

**Comment by nrk** [comment]
@b1rdex I like `^7.2 || ^8.0` (note it's a double pipe for the logical OR) because it's more explicit not only as a constraint for composer but for developers as well.

**Pull request merged**
