### PR TITLE
Fix ArrayHasSameValuesConstraint

### PR DESCRIPTION
**Pull request by b1rdex**

### CODE REVIEW

**Comment by b1rdex** [comment]
Sorry for the mess :D Worked on the web interface.

**Comment by b1rdex** [comment]
Oh well... PHPUnit update broke everything.

**Comment by tillkruss** [comment]
@b1rdex: No worries, we can always squash and merge. Ping me when the tests pass 👍🏻

**Comment by b1rdex** [comment]
I'm not sure whether updating PHPUnit worth it. It's not easy to rewrite the tests. Most of the things can be automated using Rector. But there are so many usages of the old `getMock()`... most of them have to be hand-rewritten.

**Pull request closed without merging**
